### ISSUE TITLE
Support generating Zsh specific completion files

### ISSUE THREAD

**Issue by postmodern** [DannyBen/completely#59]
Hello, I would like to write a command which automatically installs the completion files without any additional user interaction or configuration. Currently, I would have to request the user to enable `bashcompinit` in the users `~/.zshrc`, or I would have to prepend `autoload -Uz +X compinit && compinit` and `autoload -Uz +X bashcompinit && bashcompinit` to each completion file, so that the completion files can be directly installed into Zsh's `site-functions` directory.

If it would be possible to generate a separate Bash and Zsh completion files, it would make it easier to automatically install them based on the `SHELL` environment variable.

**Comment by DannyBen** [comment]
I understand the annoyance.

As I understand, zsh completion scripts are completely different (no pun intended).

I would expect that zsh support bash completions out of the box (i.e. without requiring the user to do something). Otherwise, the next simplest solution is to have your own setup script to put things in their place.

That said, I am open to seeing examples / code of how this situation can be improved, assuming the solution is simple and elegant.

**Comment by postmodern** [comment]
> I would expect that zsh support bash completions out of the box (i.e. without requiring the user to do something).

Testing locally on Fedora, zsh doesn't have `bashcompinit` loaded by default. So I have to run the Zsh setup code.

```
[postmodern@dev]~/code/ronin-rb/ronin% source data/completions/ronin 
bash: complete: command not found...
[postmodern@dev]~/code/ronin-rb/ronin% autoload -Uz +X compinit && compinit
autoload -Uz +X bashcompinit && bashcompinit
[postmodern@dev]~/code/ronin-rb/ronin% source data/completions/ronin       
[postmodern@dev]~/code/ronin-rb/ronin% 
```

I recent made [command_kit-completion](https://github.com/postmodern/command_kit-completion) which generates the completion rules and feeds them to `Completely`. I could patch it to support generating separate files for bash and zsh, with this additional code prepended to the top for zsh:

```shell
if ! command -v bashcompinit 2>/dev/null; then
  autoload -Uz +X compinit && compinit
  autoload -Uz +X bashcompinit && bashcompinit
fi
```

**Comment by DannyBen** [comment]
- Generating separate files does not feel right. The problem is with the installation process, not the script.
- I understand Oh-My-Zsh fixes this and other zsh "issues"?
- Everywhere I see the `autoload` for bash completions, it is mentioned that this should be in an initialization script and not in a completion script. 
- Is there any example of a completion script for an established CLI that injects this (or similar) condition to it?

**Comment by postmodern** [comment]
Based on [a poll I did on Mastodon](https://infosec.exchange/@postmodern/111604297867337993), certain people really do not like the idea of an automated tool editing their `~/.zshrc`. So any additional configuration to enable `bashcompinit` has to be embedded into the completion files themselves, to avoid any sort of out-of-order loading of `site-functions` files, and then copied into `zsh/site-functions/`. You can test the above code yourself. It should only run once.

I can't think of another `completion` sub-command that installs shell completions off the top of my head. I've been trying to find examples.

**Comment by postmodern** [comment]
Alternatively, such a `completion` command could by default install the shell completion files into the bash completions directory, then print out additional configuration instructions for zsh users on how to enable bash completions. However, this seems like additional work and kind of unfair to zsh users.

**Comment by DannyBen** [comment]
Am I wrong in expecting that zsh itself should handle this common scenario? Actually, two common scenarios:

1. Nobody likes to have their `~/.bashrc` or `~/.zshrc` messed with. Solution: Have a `~/.zshrc.d` and have `~/.zshrc` load everything from it. It will allow installation scripts to simply drop files in this directory (I did this for myself [here](https://github.com/DannyBen/rush-repo/blob/master/bashrc/main), but of course I am talking about a universally accepted solution, not a personal implementation)
2. In regards to bash completions, I am expecting zsh to autoload these commands out of the box. Zsh should make itself compatible with bash in this (and other) regards, especially since it seems quite simple to do so.

**Comment by DannyBen** [comment]
> Alternatively, such a `completion` command could by default install the shell completion files into the bash completions directory, then print out additional configuration instructions for zsh users on how to enable bash completions. However, this seems like additional work and kind of unfair to zsh users.

Well, this is your choice in your installation command, which brings us back to it being a) an installation issue and b) a zsh issue.

With the number of times I had this discussion with zsh users, I would expect users to either stop using zsh or for zsh to fix this shortcoming. It is clearly a bad user experience, and zsh users will have this with all programs that bring bash completion scripts.

Anyways - completely is a **bash completsions** generator by design, not a multi-shell completions generator. Bash completion script should be supported by all shells - with more or less setup steps.
